num1_rda = float(input("Enter first number: "))
num2_rda = float(input("Enter second number: "))
print("Addition:", num1_rda + num2_rda)
print("Subtraction:", num1_rda - num2_rda)
print("Multiplication:", num1_rda * num2_rda)
print("Division:", num1_rda / num2_rda)
