name_rda = input("Enter your name: ")
age_rda = input("Enter your age: ")
course_rda = input("Enter your course: ")
university_rda = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_rda)
print("Age:", age_rda)
print("Course:", course_rda)
print("University:", university_rda)